#ifndef CONSOLECOLORCODE_H_INCLUDED
#define CONSOLECOLORCODE_H_INCLUDED

#define EMPTY 			-1
#define BLACK  			0
#define BLUE 			1
#define GREEN 			2
#define CYAN 			3
#define RED 			4
#define PURPLE 			5
#define YELLOW 			6
#define WHITE 			7
#define GRAY 			8
#define B_BLUE 			9
#define B_GREEN 		10
#define B_CYAN			11
#define B_RED			12
#define B_PURPLE		13
#define B_YELLOW		14
#define B_WHITE			15
#define BLACK_BLUE		16
#define BLUE_BLUE		17
#define GREEN_BLUE		18
#define CYAN_BLUE		19
#define RED_BLUE		20
#define PURPLE_BLUE		21
#define YELLOW_BLUE		22
#define WHITE_BLUE		23
#define GRAY_BLUE		24
#define B_BLUE_BLUE		25
#define B_GREEN_BLUE	26
#define B_CYAN_BLUE		27
#define B_RED_BLUE		28
#define B_PURPLE_BLUE	29
#define B_YELLOW_BLUE	30
#define B_WHITE_BLUE	31
#define BLACK_GREEN		32
#define BLUE_GREEN		33
#define GREEN_GREEN		34
#define CYAN_GREEN		35
#define RED_GREEN		36
#define PURPLE_GREEN	37
#define YELLOW_GREEN	38
#define WHITE_GREEN		39
#define GRAY_GREEN		40
#define B_BLUE_GREEN	41
#define B_GREEN_GREEN	42
#define B_CYAN_GREEN	43
#define B_RED_GREEN		44
#define B_PURPLE_GREEN	45
#define B_YELLOW_GREEN	46
#define B_WHITE_GREEN	47
#define BLACK_CYAN		48
#define BLUE_CYAN		49
#define GREEN_CYAN		50
#define CYAN_CYAN		51
#define RED_CYAN		52
#define PURPLE_CYAN		53
#define YELLOW_CYAN		54
#define WHITE_CYAN		55
#define GRAY_CYAN		56
#define B_BLUE_CYAN		57
#define B_GREEN_CYAN	58
#define B_CYAN_CYAN		59
#define B_RED_CYAN		60
#define B_PURPLE_CYAN	61
#define B_YELLOW_CYAN	62
#define B_WHITE_CYAN	63
#define BLACK_RED		64
#define BLUE_RED		65
#define GREEN_RED		66
#define CYAN_RED		67
#define RED_RED			68
#define PURPLE_RED		69
#define YELLOW_RED		70
#define WHITE_RED		71
#define GRAY_RED		72
#define B_BLUE_RED		73
#define B_GREEN_RED		74
#define B_CYAN_RED		75
#define B_RED_RED		76
#define B_PURPLE_RED	77
#define B_YELLOW_RED	78
#define B_WHITE_RED		79
#define BLACK_PURPLE	80
#define BLUE_PURPLE		81
#define GREEN_PURPLE	82
#define CYAN_PURPLE		83
#define RED_PURPLE		84
#define PURPLE_PURPLE	85
#define YELLOW_PURPLE	86
#define WHITE_PURPLE	87
#define GRAY_PURPLE		88
#define B_BLUE_PURPLE	89
#define B_GREEN_PURPLE	90
#define B_CYAN_PURPLE	91
#define B_RED_PURPLE	92
#define B_PURPLE_PURPLE	93
#define B_YELLOW_PURPLE	94
#define B_WHITE_PURPLE	95
#define BLACK_YELLOW	96
#define BLUE_YELLOW		97
#define GREEN_YELLOW	98
#define CYAN_YELLOW		99
#define RED_YELLOW		100
#define PURPLE_YELLOW	101
#define YELLOW_YELLOW	102
#define WHITE_YELLOW	103
#define GRAY_YELLOW		104
#define B_BLUE_YELLOW	105
#define B_GREEN_YELLOW	106
#define B_CYAN_YELLOW	107
#define B_RED_YELLOW	108
#define B_PURPLE_YELLOW	109
#define B_YELLOW_YELLOW	110
#define B_WHITE_YELLOW	111
#define BLACK_WHITE		112
#define BLUE_WHITE		113
#define GREEN_WHITE		114
#define CYAN_WHITE		115
#define RED_WHITE		116
#define PURPLE_WHITE	117
#define YELLOW_WHITE	118
#define WHITE_WHITE		119
#define GRAY_WHITE		120
#define B_BLUE_WHITE	121
#define B_GREEN_WHITE	122
#define B_CYAN_WHITE	123
#define B_RED_WHITE		124
#define B_PURPLE_WHITE	125
#define B_YELLOW_WHITE	126
#define B_WHITE_WHITE	127
#define BLACK_GRAY		128
#define BLUE_GRAY		129
#define GREEN_GRAY		130
#define CYAN_GRAY		131
#define RED_GRAY		132
#define PURPLE_GRAY		133
#define YELLOW_GRAY		134
#define WHITE_GRAY		135
#define GRAY_GRAY		136
#define B_BLUE_GRAY		137
#define B_GREEN_GRAY	138
#define B_CYAN_GRAY		139
#define B_RED_GRAY		140
#define B_PURPLE_GRAY	141
#define B_YELLOW_GRAY	142
#define B_WHITE_GRAY	143
#define  BLACK_B_BLUE	144
#define BLUE_B_BLUE		145
#define GREEN_B_BLUE	146
#define CYAN_B_BLUE		147
#define RED_B_BLUE		148
#define PURPLE_B_BLUE	149
#define YELLOW_B_BLUE	150
#define WHITE_B_BLUE	151
#define GRAY_B_BLUE		152
#define B_BLUE_B_BLUE	153
#define B_GREEN_B_BLUE	154
#define B_CYAN_B_BLUE	155
#define B_RED_B_BLUE	156
#define B_PURPLE_B_BLUE	157
#define B_YELLOW_B_BLUE	158
#define B_WHITE_B_BLUE	159
#define BLACK_B_GREEN	160
#define BLUE_B_GREEN	161
#define GREEN_B_GREEN	162
#define CYAN_B_GREEN	163
#define RED_B_GREEN		164
#define PURPLE_B_GREEN	165
#define YELLOW_B_GREEN	166
#define WHITE_B_GREEN	167
#define GRAY_B_GREEN	168
#define B_BLUE_B_GREEN	169
#define B_GREEN_B_GREEN	170
#define B_CYAN_B_GREEN	171
#define B_RED_B_GREEN	172
#define B_PURPLE_B_GREEN 173
#define B_YELLOW_B_GREEN 174
#define B_WHITE_B_GREEN	175
#define BLACK_B_CYAN	176
#define BLUE_B_CYAN		177
#define GREEN_B_CYAN	178
#define CYAN_B_CYAN		179
#define RED_B_CYAN		180
#define PURPLE_B_CYAN	181
#define YELLOW_B_CYAN	182
#define WHITE_B_CYAN	183
#define GRAY_B_CYAN		184
#define B_BLUE_B_CYAN	185
#define B_GREEN_B_CYAN	186
#define B_CYAN_B_CYAN	187
#define B_RED_B_CYAN	188
#define B_PURPLE_B_CYAN	189
#define B_YELLOW_B_CYAN	190
#define B_WHITE_B_CYAN	191
#define BLACK_B_RED		192
#define BLUE_B_RED		193
#define GREEN_B_RED		194
#define CYAN_B_RED		195
#define RED_B_RED		196
#define PURPLE_B_RED	197
#define YELLOW_B_RED	198
#define WHITE_B_RED		199
#define GRAY_B_RED		200
#define B_BLUE_B_RED	201
#define B_GREEN_B_RED	202
#define B_CYAN_B_RED	203
#define B_RED_B_RED		204
#define B_PURPLE_B_RED	205
#define B_YELLOW_B_RED	206
#define B_WHITE_B_RED	207
#define BLACK_B_PURPLE	208
#define BLUE_B_PURPLE	209
#define GREEN_B_PURPLE	210
#define CYAN_B_PURPLE	211
#define RED_B_PURPLE	212
#define PURPLE_B_PURPLE	213
#define YELLOW_B_PURPLE	214
#define WHITE_B_PURPLE	215
#define GRAY_B_PURPLE	216
#define B_BLUE_B_PURPLE	217
#define B_GREEN_B_PURPLE 218
#define B_CYAN_B_PURPLE	219
#define B_RED_B_PURPLE	220
#define B_PURPLE_B_PURPLE 221
#define B_YELLOW_B_PURPLE 222
#define B_WHITE_B_PURPLE 223
#define BLACK_B_YELLOW	224
#define BLUE_B_YELLOW	225
#define GREEN_B_YELLOW	226
#define CYAN_B_YELLOW	227
#define RED_B_YELLOW	228
#define PURPLE_B_YELLOW	229
#define YELLOW_B_YELLOW	230
#define WHITE_B_YELLOW	231
#define GRAY_B_YELLOW	232
#define B_BLUE_B_YELLOW	233
#define B_GREEN_B_YELLOW 234
#define B_CYAN_B_YELLOW	235
#define B_RED_B_YELLOW	236
#define B_PURPLE_B_YELLOW 237
#define B_YELLOW_B_YELLOW 238
#define B_WHITE_B_YELLOW 239
#define BLACK_B_WHITE	240
#define BLUE_B_WHITE	241
#define GREEN_B_WHITE	242
#define CYAN_B_WHITE	243
#define RED_B_WHITE		244
#define PURPLE_B_WHITE	245
#define YELLOW_B_WHITE	246
#define WHITE_B_WHITE	247
#define GRAY_B_WHITE	248
#define B_BLUE_B_WHITE	249
#define B_GREEN_B_WHITE	250
#define B_CYAN_B_WHITE	251
#define B_RED_B_WHITE	252
#define B_PURPLE_B_WHITE 253
#define B_YELLOW_B_WHITE 254
#define B_WHITE_B_WHITE 255

#endif // CONSOLECOLORCODE_H_INCLUDED
